build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - command: 'vendor/bin/phpunit --coverage-clover=coverage-report'
            coverage:
              file: 'coverage-report'
              format: 'clover'
  environment:
    php:
      version: 8.1.1
